# Generated by Django 3.1.7 on 2021-03-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_auto_20210329_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
