# Generated by Django 3.1.7 on 2021-03-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_auto_20210329_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Free',
        ),
    ]
