# Generated by Django 3.1.7 on 2021-03-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0005_auto_20210330_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='avi_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='free',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='free',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
